project:
  type: book
  output-dir: docs


book:
  title: "A first course in biostatistics"
  author: "coming soon"
  date: "10/5/2023"
  chapters:
    - index.qmd
    - software_setup.qmd
    - intro_process_models.qmd
    - coding_neutral_theory.qmd
    - neutral_theory_sims.qmd
    - ml_inference_neutral.qmd
    - day_1_wrapup.qmd
    - intro_mess.qmd
    - mess_getting_started.qmd
    - mess_simulations.qmd
    - ml_inference_classification.qmd
    - ml_inference_regression.qmd
    - wrapup.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: cosmo



